Fix: 이미지 Entity 수정 및 DTO 구조 변경
MinWonHaeSo/ESC_SERVER pull request #34
Opened 2022-12-07 14:35 UTC by dongjji

### Background
---
- 프론트 쪽에서 Cloudinary 이미지를 삭제하기 위해 public_id값이 필요하여 디비에 같이 저장하기 위해 엔티티 수정이 필요했음.
- DTO파일을 너무 막 만들었다는 생각이 들어서 수정이 필요했음.

### Change
---
- [X] Entity 및 DTO 내용도 수정 완료
- [X] Entity 별로 묶고 그 안에서 CRUD별, Request, Response별로 다시 묶었습니다

### Analytics
---
- Postman으로 CRUD Test 했습니다. 추후에 테스트코드 작성하겠습니다!

### Discuss
---
- DTO쪽은 구조만 변경한 상태라 파일명이나 구조들만 봐주시면 될 것 같습니다!
- Entity쪽에는 img의 id값만 추가한 상태이며 이 id값은 Cloudinary에서 사용하는 이미지에 대한 PK인 걸로 알고 있습니다. 다만, 저희도 이 id를 PK로 사용해야될지는 잘 모르겠어서 일단 추가 컬럼으로 넣었습니다!

2022-12-07 16:26 UTC, SoA-Lee approved these changes
파일명과 구조 모두 확인하였습니다! 추후 API 구현 시 참고하겠습니다👍 고생하셨어요 동준님!

2022-12-07 16:26 UTC, SoA-Lee commented on src/main/java/com/minwonhaeso/esc/stadium/service/StadiumService.java
> +    public CreateStadiumResponse createStadium(StadiumDto.CreateStadiumRequest request) {
도메인 DTO 안에 세부 Request랑 Response로 생성하니 훨씬 깔끔한 것 같아요! 좋은 방법인 것 같습니다.

2022-12-08 03:05 UTC, phc09188 reviewed
수고하셨습니다. Dto 정리도 깔끔하게 보여서 좋은 것 같아요! Dto 쪽에서 ApiModel을 사용하는 부분은 저도 추가해야겠군요!

2022-12-08 03:06 UTC, phc09188 requested changes

2022-12-08 03:06 UTC, phc09188 commented on build.gradle
>      implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
build.gradle은 원래대로 돌려 놓는게 좋을 것 같아요!

2022-12-08 03:41 UTC, dongjji commented on build.gradle
>      implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
위에 줄이랑 똑같은 코드가 들어가 있어서 삭제했습니다!

2022-12-09 00:01 UTC, phc09188 approved these changes

2022-12-09 00:01 UTC, merged